name: suturaapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  assets: ^0.0.2
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/suturalogo.jpeg"